#ifndef CONFIG_H
#define CONFIG_H

#define WIFI_SSID "Afishchan"
#define WIFI_PASSWORD "Afish@2005"

#define SERVER_URL "http://10.17.146.237:5000"
#define DEVICE_ID "esp32_cam_01"

#define API_HEALTH_PATH "/health"
#define API_RFID_START_SESSION_PATH "/api/rfid/start-session"
#define API_ESP32_FRAME_PATH "/api/esp32/frame"
#define API_SESSION_STOP_PATH "/api/session/stop"

#define RFID_UID_FIELD_NAME "rfid_uid"
#define ESP32_FRAME_FIELD_NAME "frame"

#define USE_DUMMY_FRAME_DATA true
#define AUTO_START_SESSION_WITH_TEST_RFID true
#define TEST_RFID_UID "123456"

// Tiny valid 1x1 JPEG in Base64 for dummy mode
#define DUMMY_FRAME_BASE64 \
    "/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxAQEBAPEA8QEA8QDw8PDw8QDw8PDw8PFREWFhURFRUYHSggGBolGxUVITEhJSkrLi4uFx8zODMsNygtLisBCgoKDg0OGhAQGi0lHyUtLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLS0tLf/AABEIAAEAAQMBIgACEQEDEQH/xAAXAAEBAQEAAAAAAAAAAAAAAAAAAQID/8QAFhEBAQEAAAAAAAAAAAAAAAAAABEB/9oADAMBAAIQAxAAAAG9gB//xAAWEAEBAQAAAAAAAAAAAAAAAAAAARH/2gAIAQEAAT8Aqf/EABYRAQEBAAAAAAAAAAAAAAAAAAABEf/aAAgBAgEBPwCn/8QAFhEBAQEAAAAAAAAAAAAAAAAAABEB/9oACAEDAQE/AKf/2Q=="

#define RFID_SS_PIN 15
#define RFID_RST_PIN 2
#define RFID_SCK_PIN 14
#define RFID_MISO_PIN 12
#define RFID_MOSI_PIN 13

#define DEFAULT_SESSION_DURATION 15 // minutes
#define PHOTO_CAPTURE_INTERVAL 5000 // milliseconds
#define MAX_RETRY_ATTEMPTS 3
#define RETRY_DELAY_MS 1000
#define WIFI_CONNECT_TIMEOUT_MS 30000
#define BACKEND_HEALTH_CHECK_INTERVAL_MS 30000

#define FLASH_LED_PIN 4
#define STATUS_LED_PIN -1

#define CAMERA_MODEL_ESP32CAM
#define CAMERA_JPEG_QUALITY 12
#define CAMERA_FRAME_SIZE FRAMESIZE_QVGA
#define CAMERA_FB_COUNT 2

#endif
