[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200

lib_deps =
    miguelPRO/ESP32 Camera Driver@^1.0
    miguelPRO/ESP32 Camera Servo@^1.0
    mrfetch/MFRC522@^1.4.10

build_flags =
    -DCORE_DEBUG_LEVEL=4
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1

upload_speed = 921600
